- name: Layer-2 Interfaces
  hosts: switches
  tasks:
    - name: Switchport VLAN Assignment
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            access:
              vlan: "{{ item.vlan_id }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', vlan_id: 10 }

    - name: Configure Trunk Parameters
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            trunk:
              allowed_vlans: 10,20,30
              encapsulation: dot1q
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/2'}
        - { interface_name: 'GigabitEthernet0/3'}

    - name: Configuring Switch Modes
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            mode: "{{ item.mode }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', mode: access }
        - { interface_name: 'GigabitEthernet0/2', mode: trunk }
        - { interface_name: 'GigabitEthernet0/3', mode: trunk }

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified

- name: Layer-3 interfaces
  hosts: routers
  tasks:
    - name: Configure L3 IP Addresses
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ interface_1_name }}"
            ipv4:
              - address: "{{ interface_1_ip }}"
          - name: "{{ interface_2_name }}"
            ipv4:
              - address: "{{ interface_2_ip }}"
          - name: Loopback0
            ipv4:
              - address: "{{ loopback_ip }}"
        state: merged
    - name: Enable Interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            enabled: true
      loop:
        - { interface_name: 'GigabitEthernet0/1' }
        - { interface_name: 'GigabitEthernet0/2' }
        - { interface_name: 'GigabitEthernet0/3' }  
    - name: Configure OSPF with loopback as router ID
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              router_id: "{{ loopback_ip.split('/')[0] }}"
              network:
                - address: "{{ interface_1_ip.split('/')[0] }}"
                  wildcard_bits: "0.0.0.0"
                  area: 0
                - address: "{{ interface_2_ip.split('/')[0] }}"
                  wildcard_bits: "0.0.0.0"
                  area: 0
                - address: "{{ loopback_ip.split('/')[0] }}"
                  wildcard_bits: "0.0.0.0"
                  area: 0
        state: merged
    - name: WAN Facing ACL Configuration
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: WAN_ACL
                aces:
                  - sequence: 10
                    grant: deny
                    protocol: ip
                    source:
                      any: true
                    destination: 
                      address: 192.168.1.0
                      wildcard_bits: 0.0.0.255
        state: merged
    - name: Apply ACL to WAN interface (inbound)
      cisco.ios.ios_acls_interfaces:
        config:
          - name: "{{ item }}"
            access_groups:
              - afi: ipv4
                acls:
                  - name: WAN_ACL
                  - direction: in        
        state: merged
      loop:
        - GigabitEthernet0/2
    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified 
