- name: Layer-2 Interfaces
  hosts: switches
  tasks:
    - name: Switchport VLAN Assignment
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            access:
              vlan: "{{ item.vlan_id }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', vlan_id: 10 }

    - name: Configure Trunk Parameters
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            trunk:
              allowed_vlans: 10,20,30
              encapsulation: dot1q
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/2'}
        - { interface_name: 'GigabitEthernet0/3'}

    - name: Configuring Switch Modes
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            mode: "{{ item.mode }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', mode: access }
        - { interface_name: 'GigabitEthernet0/2', mode: trunk }
        - { interface_name: 'GigabitEthernet0/3', mode: trunk }

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified

- name: Layer-3 interfaces
  hosts: routers
  tasks:
    - name: Configure Layer-3 interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet0/3
            ipv4:
              - address: "{{ gi3addr }}"
    - name: Enable Interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            enabled: true
      loop:
        - { interface_name: 'GigabitEthernet0/1' }
        - { interface_name: 'GigabitEthernet0/2' }
        - { interface_name: 'GigabitEthernet0/3' }  
    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified 
