- name: Layer-2 Interfaces
  hosts: switches
  tasks:
    - name: Switchport VLAN Assignment
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            access:
              vlan: "{{ item.vlan_id }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', vlan_id: 10 }

    - name: Configure Trunk Parameters
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            trunk:
              allowed_vlans: 10,20,30
              encapsulation: dot1q
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/2'}
        - { interface_name: 'GigabitEthernet0/3'}

    - name: Configuring Switch Modes
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            mode: "{{ item.mode }}"
        state: merged
      loop:
        - { interface_name: 'GigabitEthernet0/1', mode: access }
        - { interface_name: 'GigabitEthernet0/2', mode: trunk }
        - { interface_name: 'GigabitEthernet0/3', mode: trunk }

    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified

- name: Layer-3 interfaces
  hosts: routers
  tasks:
    - name: Configure L3 IP Addresses
      cisco.ios.ios_l3_interfaces:
       config: "{{ hostvars[inventory_hostname]['interface_configs'] | from_json }}"
       state: merged
    - name: Enable Interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.interface_name }}"
            enabled: true
      loop:
        - { interface_name: 'GigabitEthernet0/1' }
        - { interface_name: 'GigabitEthernet0/2' }
        - { interface_name: 'GigabitEthernet0/3' }  
    - name: Configure OSPF with loopback as router ID
      cisco.ios.ios_ospf:
        config:
          - process_id: 1
            router_id: "{{ router_id }}"
            network:
              - address: 192.168.1.0
                wildcard_bits: 0.0.0.255
                area: 0
              - address: 10.0.0.0
                wildcard_bits: 0.0.0.255
                area: 0
              - address: "{{ (interface_configs | from_json | selectattr('name', 'equalto', 'Loopback0') | first).ip.split('/')[0] }}"
                wildcard_bits: 0.0.0.0
                area: 0
        state: merged
    - name: Apply ACL to WAN interfaces
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            name: WAN_ACL
            aces:
              - sequence: 10
                action: permit
                protocol: ip
                source: any
                destination: any
        state: merged
    - name: Attach ACL to WAN interface (inbound)
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item }}"
            ipv4:
              access_group:
                in: WAN_ACL
        state: merged
      loop:
        - GigabitEthernet0/2
    - name: Save configuration
      cisco.ios.ios_config:
        save_when: modified 
